steps:

  # Carry out some basic linting across the codebase.
  - name: "linting"
    command:
      - "/app/.buildkite/scripts/linting.sh"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"
      - ecr#v2.2.0:
          login: true
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml

  - wait

  # Build and run the AWS Lambda Function tests.
  - name: "aws-lambda-tests"
    command:
      - ". /app/.buildkite/scripts/init-environment.sh"
      - "yarn install"
      - "yarn build"
      - "yarn test"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"
      - ecr#v2.2.0:
          login: true
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BRANCH
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN

  - wait

  # Package and persist the Auth0 scripts.
  - name: "auth0-packaging"
    command:
      - ". /app/.buildkite/scripts/init-environment.sh"
      - "yarn install"
      - "yarn build-auth0-actions"
      - "/app/.buildkite/scripts/auth0-packaging.sh"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"
      - ecr#v2.2.0:
          login: true
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BRANCH
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN

  # Package and persist the AWS Lambda Functions.
  - name: "aws-lambda-packaging"
    command:
      - ". /app/.buildkite/scripts/init-environment.sh"
      - "yarn install"
      - "yarn build"
      - "yarn package-api-templates"
      - "/app/.buildkite/scripts/aws-lambda-packaging.sh"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"
      - ecr#v2.2.0:
          login: true
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BRANCH
            - BUILDKITE_COMMIT
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN

  - wait

  # Deploy to stage
  - name: "deploy-stage"
    branches: "main"
    trigger: "identity-deploy-stage"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
